name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS v14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
